import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000000",
      white: "#FFFFFF",
      bg: "#0C0E12",
      surface: "#14161B",
      "surface-raised": "#1C1F27",
      "surface-overlay": "#242833",
      text: "#E8E9EC",
      "text-secondary": "#9BA3AF",
      "text-tertiary": "#6B7280",
      border: "#2A2E38",
      "border-subtle": "#1E2128",
      accent: "#5B8DEF",
      "accent-hover": "#7AA4F2",
      "accent-muted": "#2A3A5C",
      success: "#4ADE80",
      "success-muted": "#1A3A2A",
      warning: "#FBBF24",
      "warning-muted": "#3A3010",
      danger: "#F87171",
      "danger-muted": "#3A1A1A",
      "status-draft": "#6B7280",
      "status-applied": "#5B8DEF",
      "status-interviewing": "#A78BFA",
      "status-interviewing-muted": "#3A305C",
      "status-offer": "#4ADE80",
      "status-closed": "#F87171",
    },
    fontFamily: {
      sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
      mono: ["var(--font-geist-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
    },
    fontSize: {
      caption: ["11px", { lineHeight: "1.4" }],
      label: ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
      small: ["13px", { lineHeight: "1.5" }],
      body: ["14px", { lineHeight: "1.5" }],
      subheading: ["16px", { lineHeight: "1.4", fontWeight: "500" }],
      heading: ["20px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
      display: ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
    },
    borderRadius: { none: "0", sm: "4px", md: "6px", lg: "8px", xl: "12px", full: "9999px" },
    spacing: {
      0: "0",
      px: "1px",
      xs: "4px",
      sm: "8px",
      md: "12px",
      lg: "16px",
      xl: "24px",
      "2xl": "32px",
      "3xl": "48px",
      ...Object.fromEntries(Array.from({ length: 13 }, (_, i) => [i, `${i * 4}px`])),
    },
    extend: {
      ringWidth: { "2": "2px" },
    },
  },
  plugins: [],
};

export default config;
